name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Get repo name
        id: repo_name
        run: |
          name = echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]'
          echo "name=$name" >> $GITHUB_ENV

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Cache Docker layers
        uses: actions/cache@v3.2.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.repo_name.outputs.name }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64,
            linux/arm64

          cache-from: |
            type=local,
            src=/tmp/.buildx-cache

          cache-to: |
            type=local,
            dest=/tmp/.buildx-cache

      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ steps.repo_name.outputs.name }}:${{ steps.meta.outputs.tags }}